server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        boot:
          allow_jdbc_metadata_access: false
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

api:
  security:
    token:
      secret: my-secret-key

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
